# GitHub Copilot Coding Agent Configuration
# This file configures how the Copilot coding agent behaves when
# delegated tasks via issues, CLI, or VS Code.

# Agent behavior settings
agent:
  # Maximum number of files the agent can modify per task
  max_files_modified: 20
  
  # Maximum lines of code changes per task
  max_lines_changed: 500
  
  # Allow agent to create new files
  allow_file_creation: true
  
  # Allow agent to delete files
  allow_file_deletion: false
  
  # Allow agent to modify configuration files
  allow_config_changes: true
  
  # Require tests for new code
  require_tests: true
  
  # Minimum test coverage for new code (percentage)
  min_test_coverage: 80

# Boundaries and restrictions
boundaries:
  # Directories the agent can modify
  allowed_paths:
    - "src/**"
    - "tests/**"
    - "docs/**"
    - "scripts/**"
  
  # Directories the agent cannot modify
  excluded_paths:
    - ".github/workflows/**"
    - ".github/copilot/**"
    - "infrastructure/**"
    - "*.lock"
    - "*.env*"
  
  # File patterns the agent cannot modify
  excluded_patterns:
    - "**/*.pem"
    - "**/*.key"
    - "**/secrets/**"
    - "**/credentials/**"
  
  # Maximum file size the agent will modify (KB)
  max_file_size_kb: 100

# Code quality requirements
quality:
  # Run linter before submitting PR
  run_linter: true
  
  # Run type checker before submitting PR
  run_type_check: true
  
  # Run tests before submitting PR
  run_tests: true
  
  # Require all checks to pass
  require_all_checks_pass: true

# Commit settings
commits:
  # Commit message prefix for agent commits
  message_prefix: "feat(agent):"
  
  # Sign commits (requires configured GPG)
  sign_commits: false
  
  # Create atomic commits (one per logical change)
  atomic_commits: true

# Pull request settings
pull_request:
  # PR title prefix
  title_prefix: "[Agent]"
  
  # Add labels to agent PRs
  labels:
    - "agent-generated"
    - "needs-review"
  
  # Assign reviewers automatically
  auto_assign_reviewers: true
  
  # Request review from CODEOWNERS
  request_codeowners_review: true
  
  # Create as draft PR
  draft: true
  
  # PR body template
  body_template: |
    ## Summary
    {description}
    
    ## Changes Made
    {changes}
    
    ## Testing
    - [ ] Unit tests added/updated
    - [ ] Integration tests added/updated
    - [ ] Manual testing performed
    
    ## Checklist
    - [ ] Code follows project conventions
    - [ ] Documentation updated
    - [ ] No secrets or sensitive data
    
    ---
    *This PR was generated by GitHub Copilot coding agent.*
    *Please review carefully before merging.*

# Environment configuration
environment:
  # Use specific Node.js version
  node_version: "20"
  
  # Use specific Python version
  python_version: "3.11"
  
  # Install dev dependencies
  install_dev_dependencies: true
  
  # Setup commands to run before task
  setup_commands:
    - "npm ci || yarn install --frozen-lockfile || pnpm install --frozen-lockfile"
    - "pip install -r requirements.txt || pip install -e ."

# Timeout settings (in minutes)
timeouts:
  # Maximum time for a single task
  task_max: 30
  
  # Maximum time for setup
  setup_max: 10
  
  # Maximum time for tests
  test_max: 15

# Logging and monitoring
logging:
  # Log level for agent output
  level: "info"
  
  # Include detailed trace logs
  trace: false
  
  # Log to file
  log_file: ".copilot/agent.log"
